export * from './signUpPages';
export * from './signInPage';
export * from './mainPage';
export * from './aboutPage';
export * from './animePage';
export * from './top100Page';
export * from './searchListPage';
export * from './homePage';
export * from './genrePage';